//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.DataModelGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.DataModelGenerator.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character ranges must specify single characters for their begin and end..
        /// </summary>
        internal static string CharacterRangeBadCharacterCount {
            get {
                return ResourceManager.GetString("CharacterRangeBadCharacterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character range must have only one character to begin and end the range, but zero or greater than 1 characters reported..
        /// </summary>
        internal static string CharacterRangeMustHaveSingleCharacterStartAndEnd {
            get {
                return ResourceManager.GetString("CharacterRangeMustHaveSingleCharacterStartAndEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate C# argument name &apos;{0}&apos; declared..
        /// </summary>
        internal static string DuplicateArgumentName {
            get {
                return ResourceManager.GetString("DuplicateArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate C# member name &apos;{0}&apos; declared..
        /// </summary>
        internal static string DuplicateCSharpMemberName {
            get {
                return ResourceManager.GetString("DuplicateCSharpMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate JSON member name &apos;{0}&apos; declared..
        /// </summary>
        internal static string DuplicateJsonMemberName {
            get {
                return ResourceManager.GetString("DuplicateJsonMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one identifier, string, character range, or enclosed sub-alternation must be present here..
        /// </summary>
        internal static string EmptyGroup {
            get {
                return ResourceManager.GetString("EmptyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos; here..
        /// </summary>
        internal static string ExpectedStringHere {
            get {
                return ResourceManager.GetString("ExpectedStringHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Failed to compile production.
        /// </summary>
        internal static string FailedToCompileProduction {
            get {
                return ResourceManager.GetString("FailedToCompileProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character range must start with the &apos;lower&apos; character and end with the greater character. Try reversing these..
        /// </summary>
        internal static string FirstCharacterInCharacterRangeMustBeLower {
            get {
                return ResourceManager.GetString("FirstCharacterInCharacterRangeMustBeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grammar declaration was expected here..
        /// </summary>
        internal static string GrammarExpectedHere {
            get {
                return ResourceManager.GetString("GrammarExpectedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not indent code further; is already indented too far..
        /// </summary>
        internal static string IndentedTooDeep {
            get {
                return ResourceManager.GetString("IndentedTooDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to un-indent code when the indent level is already zero; indent/unindent s mismatched..
        /// </summary>
        internal static string IndentMismatch {
            get {
                return ResourceManager.GetString("IndentMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical text is not available for this symbol type..
        /// </summary>
        internal static string LogicalTextNotAvailable {
            get {
                return ResourceManager.GetString("LogicalTextNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier may not contain the quote character..
        /// </summary>
        internal static string QuoteInIdentifier {
            get {
                return ResourceManager.GetString("QuoteInIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to &quot;require&quot; an invalid token (TokenKind.Default).
        /// </summary>
        internal static string RequiredInvalidToken {
            get {
                return ResourceManager.GetString("RequiredInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . was unexpected here. Did you mean .. ?.
        /// </summary>
        internal static string SingleDot {
            get {
                return ResourceManager.GetString("SingleDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A token character access was out of range..
        /// </summary>
        internal static string TokenAccessOutOfRange {
            get {
                return ResourceManager.GetString("TokenAccessOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is already claimed by base type &apos;{1}&apos;; base type &apos;{2}&apos; cannot claim it..
        /// </summary>
        internal static string TypeAlreadyTaken {
            get {
                return ResourceManager.GetString("TypeAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { annotation was not closed here..
        /// </summary>
        internal static string UnclosedAnnotation {
            get {
                return ResourceManager.GetString("UnclosedAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* comment was not closed here..
        /// </summary>
        internal static string UnclosedMultiLineComment {
            get {
                return ResourceManager.GetString("UnclosedMultiLineComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; string did not end here..
        /// </summary>
        internal static string UnclosedString {
            get {
                return ResourceManager.GetString("UnclosedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token {0} here..
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ was unexpected in an annotation name..
        /// </summary>
        internal static string UnrecognizedAtInAnnotation {
            get {
                return ResourceManager.GetString("UnrecognizedAtInAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not interpret production {0} as any known data model..
        /// </summary>
        internal static string UnrecognizedDataModel {
            get {
                return ResourceManager.GetString("UnrecognizedDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / was unexpected here. Did you mean // ?.
        /// </summary>
        internal static string UnrecognizedForwardSlash {
            get {
                return ResourceManager.GetString("UnrecognizedForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The derived type &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string UnresolvedDerivedType {
            get {
                return ResourceManager.GetString("UnresolvedDerivedType", resourceCulture);
            }
        }
    }
}
