pr:
- '*'

pool:
  vmImage: 'windows-latest'

jobs:
- job: NET_pipeline
  steps:
  # Restore and build solution
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: src/Sarif.Sdk.sln

  # Test solution
  - task: DotNetCoreCLI@2
    displayName: Run unit tests for netstandard2.0
    inputs:
      command: test
      projects: src/Sarif.Sdk.sln

  # Publish bld/publish folder
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: publish'
    inputs:
      PathtoPublish: '.\bld\Publish\'
      ArtifactName: publish

  # Publish bld/bin folder
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: build'
    inputs:
      PathtoPublish: '.\bld\bin\'
      ArtifactName: build

- job: npm_pipeline
  steps:
  # Build Multitool for npm
  - task: PowerShell@2
    displayName: Build Multitool for npm
    inputs:
      targetType: filePath
      filePath: ./scripts/BuildMultitoolForNpm.ps1
