pr:
- '*'

pool:
  vmImage: 'windows-latest'

jobs:
- job: NET_pipeline
  steps:
  # Build and test
  - task: PowerShell@2
    displayName: Build and Test
    inputs:
      targetType: filePath
      filePath: ./scripts/BuildAndTest.ps1
      arguments: -NoTest

  # Publish bld/publish folder
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: publish'
    inputs:
      PathtoPublish: '.\bld\Publish\'
      ArtifactName: publish

  # Publish bld/bin folder
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: build'
    inputs:
      PathtoPublish: '.\bld\bin\'
      ArtifactName: build

- job: npm_pipeline
  steps:
  # Build Multitool for npm
  - task: PowerShell@2
    displayName: Build Multitool for npm
    inputs:
      targetType: filePath
      filePath: ./scripts/BuildMultitoolForNpm.ps1
