pr:
  - "main"

jobs:
  - job: NET_pipeline
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-20.04"
        mac:
          imageName: "macOS-latest"
        windows:
          imageName: "windows-latest"
      maxParallel: 4

    pool:
      vmImage: $(imageName)

    steps:
      - task: UseDotNet@2
        displayName: .NET Core 3.1 sdk
        inputs:
          version: "3.1.x"
          packageType: sdk

      - task: UseDotNet@2
        displayName: .NET Core 6.0 sdk
        inputs:
          version: "6.0.x"
          packageType: sdk

      # Build and test
      - task: PowerShell@2
        displayName: Build and Test
        inputs:
          targetType: filePath
          filePath: ./scripts/BuildAndTest.ps1

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: "msbuild.binlog"
          artifactName: "binlog"

      - task: ComponentGovernanceComponentDetection@0

  - job: npm_pipeline
    pool:
      vmImage: "windows-latest"
    steps:
      # Build Multitool for npm
      - task: PowerShell@2
        displayName: Build Multitool for npm
        inputs:
          targetType: filePath
          filePath: ./scripts/BuildMultitoolForNpm.ps1
