trigger:
- 'master'

pool:
  vmImage: 'windows-latest'

jobs:
- job: NET_pipeline
  steps:
  # Build and test
  - task: PowerShell@2
    displayName: Build and Test
    inputs:
      targetType: filePath
      filePath: ./scripts/BuildAndTest.ps1
      argument: -NoPackage

  # Deleting other folders
  - task: PowerShell@2
    displayName: Deleting packages folder
    inputs:
      targetType: inline
      script: Remove-Item -recurse src\packages, src\Samples\packages, .git

  # Publish bld/bin folder
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: repo'
    inputs:
      PathtoPublish: '.'
      ArtifactName: 'repo'
      Parallel: true
      ParallelCount: 8

- job: npm_pipeline
  steps:
  # Build Multitool for npm
  - task: PowerShell@2
    displayName: Build Multitool for npm
    inputs:
      targetType: filePath
      filePath: ./scripts/BuildMultitoolForNpm.ps1
