trigger:
- master
- ado-build.yaml

pool:
  vmImage: 'ubuntu-latest'

steps:

# Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: Restore NuGet Packages
  inputs:
    command: restore
    projects: src\Sarif.Sdk.sln

