pr:
- 'main'

pool:
  vmImage: 'windows-latest'

jobs:
- job: NET_pipeline
  steps:
  # Build and test
  - task: PowerShell@2
    displayName: Build and Test
    inputs:
      targetType: filePath
      filePath: ./scripts/BuildAndTest.ps1
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'msbuild.binlog'
      artifactName: 'binlog'

- job: npm_pipeline
  steps:
  # Build Multitool for npm
  - task: PowerShell@2
    displayName: Build Multitool for npm
    inputs:
      targetType: filePath
      filePath: ./scripts/BuildMultitoolForNpm.ps1
