<?xml version="1.0" encoding="UTF-8"?>
<DEFECTS>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>11</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultSucceeded</FUNCTION>
    <DECORATED>?HResultSucceeded@@YAXJ@Z</DECORATED>
    <FUNCLINE>6</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>8</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>9</LINE>
        <COLUMN>5</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume 'SUCCEEDED(hr)')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>11</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>24</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultSucceeded2</FUNCTION>
    <DECORATED>?HResultSucceeded2@@YAXJ_N@Z</DECORATED>
    <FUNCLINE>15</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>17</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>18</LINE>
        <COLUMN>19</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Skip this branch, (assume 'SUCCEEDED(hr)&amp;&amp;b' is false)</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>24</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>33</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultSucceeded3</FUNCTION>
    <DECORATED>?HResultSucceeded3@@YAXJ_N0@Z</DECORATED>
    <FUNCLINE>28</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>30</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>31</LINE>
        <COLUMN>26</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume '((SUCCEEDED(hr)||b))&amp;&amp;c')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>33</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>42</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultSucceeded4</FUNCTION>
    <DECORATED>?HResultSucceeded4@@YAXJ@Z</DECORATED>
    <FUNCLINE>37</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>39</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>40</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume '!SUCCEEDED(_hResult)')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>42</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>51</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultFailed</FUNCTION>
    <DECORATED>?HResultFailed@@YAXJ@Z</DECORATED>
    <FUNCLINE>46</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>48</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>49</LINE>
        <COLUMN>5</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume 'FAILED(hr)')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>51</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>64</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultFailed2</FUNCTION>
    <DECORATED>?HResultFailed2@@YAXJ_N@Z</DECORATED>
    <FUNCLINE>55</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>57</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>58</LINE>
        <COLUMN>21</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Skip this branch, (assume 'FAILED(hr)&amp;&amp;b||SUCCEEDED(hr)' is false)</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>64</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>73</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultFailed3</FUNCTION>
    <DECORATED>?HResultFailed3@@YAXJ_N0@Z</DECORATED>
    <FUNCLINE>68</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>70</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>71</LINE>
        <COLUMN>25</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume '((FAILED(Hr_2)||b))&amp;&amp;c')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>73</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>82</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultFailed4</FUNCTION>
    <DECORATED>?HResultFailed4@@YAXJ@Z</DECORATED>
    <FUNCLINE>77</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>79</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>80</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume '!FAILED(hr)')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>82</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>91</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultSFalse</FUNCTION>
    <DECORATED>?HResultSFalse@@YAXJ@Z</DECORATED>
    <FUNCLINE>86</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>88</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>89</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume 'hr==S_FALSE')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>91</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>100</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultSFalse2</FUNCTION>
    <DECORATED>?HResultSFalse2@@YAXJ_N0@Z</DECORATED>
    <FUNCLINE>95</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>97</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>98</LINE>
        <COLUMN>7</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume 'b&amp;&amp;((c||S_FALSE==hr))')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>100</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>109</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultSOk</FUNCTION>
    <DECORATED>?HResultSOk@@YAXJ@Z</DECORATED>
    <FUNCLINE>104</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>106</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>107</LINE>
        <COLUMN>10</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume 'S_OK==hr')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>109</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs375867.cpp</FILENAME>
      <LINE>118</LINE>
      <COLUMN>8</COLUMN>
    </SFA>
    <DEFECTCODE>6011</DEFECTCODE>
    <DESCRIPTION>Dereferencing NULL pointer 'data'. </DESCRIPTION>
    <FUNCTION>HResultSOk2</FUNCTION>
    <DECORATED>?HResultSOk2@@YAXJ@Z</DECORATED>
    <FUNCLINE>113</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>115</LINE>
        <COLUMN>6</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>116</LINE>
        <COLUMN>20</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume '((S_FALSE+S_OK))==hr')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs375867.cpp</FILENAME>
        <LINE>118</LINE>
        <COLUMN>8</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is dereferenced, but may still be NULL</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
</DEFECTS>