<?xml version="1.0" encoding="UTF-8"?>
<DEFECTS>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\complex\c6386\</FILEPATH>
      <FILENAME>c6386example2.cpp</FILENAME>
      <LINE>7</LINE>
      <COLUMN>13</COLUMN>
    </SFA>
    <DEFECTCODE>6386</DEFECTCODE>
    <DESCRIPTION>Buffer overrun while writing to 'a':  the writable size is '80' bytes, but '84' bytes might be written.</DESCRIPTION>
    <FUNCTION>C6386_Example2</FUNCTION>
    <DECORATED>?C6386_Example2@@YAXH@Z</DECORATED>
    <FUNCLINE>1</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\complex\c6386\</FILEPATH>
        <FILENAME>c6386example2.cpp</FILENAME>
        <LINE>3</LINE>
        <COLUMN>7</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'a' is an array of 20 elements (80 bytes)</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\complex\c6386\</FILEPATH>
        <FILENAME>c6386example2.cpp</FILENAME>
        <LINE>4</LINE>
        <COLUMN>7</COLUMN>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\complex\c6386\</FILEPATH>
        <FILENAME>c6386example2.cpp</FILENAME>
        <LINE>5</LINE>
        <COLUMN>9</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>branch</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>Enter this branch, (assume 'i&lt;=21')</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\complex\c6386\</FILEPATH>
        <FILENAME>c6386example2.cpp</FILENAME>
        <LINE>7</LINE>
        <COLUMN>13</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>Invalid write to 'a[20]', (writable range is 0 to 19)</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
</DEFECTS>