/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Static Analysis Results Format (SARIF) Version 2.0.0 JSON Schema: a standard format for the output of static analysis and other tools.
 */
export interface StaticAnalysisResultsFormatSarifVersion200JsonSchema {
  /**
   * The URI of the JSON schema corresponding to the version.
   */
  $schema?: string;
  /**
   * The SARIF format version of this log file.
   */
  version: "2.0.0";
  /**
   * The set of runs contained in this log file.
   */
  runs: Run[];
}
/**
 * Describes a single run of an analysis tool, and contains the output of that run.
 */
export interface Run {
  /**
   * Information about the tool or tool pipeline that generated the results in this run. A run can only contain results produced by a single tool or tool pipeline. A run can aggregate results from multiple log files, as long as context around the tool run (tool command-line arguments and the like) is identical for all aggregated files.
   */
  tool: {
    /**
     * The name of the tool.
     */
    name: string;
    /**
     * The name of the tool along with its version and any other useful identifying information, such as its locale.
     */
    fullName?: string;
    /**
     * The tool version, in whatever format the tool natively provides.
     */
    version?: string;
    /**
     * The tool version in the format specified by Semantic Versioning 2.0.
     */
    semanticVersion?: string;
    /**
     * The binary version of the tool's primary executable file (for operating systems such as Windows that provide that information).
     */
    fileVersion?: string;
    /**
     * A version that uniquely identifies the SARIF logging component that generated this file, if it is versioned separately from the tool.
     */
    sarifLoggerVersion?: string;
    /**
     * The tool language (expressed as an ISO 649 two-letter lowercase culture code) and region (expressed as an ISO 3166 two-letter uppercase subculture code associated with a country or region).
     */
    language?: string;
    /**
     * Key/value pairs that provide additional information about the tool.
     */
    properties?: {
      /**
       * A set of distinct strings that provide additional information.
       */
      tags?: string[];
      [k: string]: any;
    };
  };
  /**
   * Describes the invocation of the analysis tool.
   */
  invocations?: Invocation[];
  /**
   * A conversion object that describes how a converter transformed an analysis tool's native output format into the SARIF format.
   */
  conversion?: {
    /**
     * A tool object that describes the converter.
     */
    tool: {
      /**
       * The name of the tool.
       */
      name: string;
      /**
       * The name of the tool along with its version and any other useful identifying information, such as its locale.
       */
      fullName?: string;
      /**
       * The tool version, in whatever format the tool natively provides.
       */
      version?: string;
      /**
       * The tool version in the format specified by Semantic Versioning 2.0.
       */
      semanticVersion?: string;
      /**
       * The binary version of the tool's primary executable file (for operating systems such as Windows that provide that information).
       */
      fileVersion?: string;
      /**
       * A version that uniquely identifies the SARIF logging component that generated this file, if it is versioned separately from the tool.
       */
      sarifLoggerVersion?: string;
      /**
       * The tool language (expressed as an ISO 649 two-letter lowercase culture code) and region (expressed as an ISO 3166 two-letter uppercase subculture code associated with a country or region).
       */
      language?: string;
      /**
       * Key/value pairs that provide additional information about the tool.
       */
      properties?: {
        /**
         * A set of distinct strings that provide additional information.
         */
        tags?: string[];
        [k: string]: any;
      };
    };
    /**
     * An invocation object that describes the invocation of the converter.
     */
    invocation?: {
      /**
       * A set of files relevant to the invocation of the tool.
       */
      attachments?: Attachment[];
      /**
       * The command line used to invoke the tool.
       */
      commandLine?: string;
      /**
       * An array of strings, containing in order the command line arguments passed to the tool from the operating system.
       */
      arguments?: string[];
      /**
       * The locations of any response files specified on the tool's command line.
       */
      responseFiles?: FileLocation[];
      /**
       * The date and time at which the run started. See "Date/time properties" in the SARIF spec for the required format.
       */
      startTime?: string;
      /**
       * The date and time at which the run ended. See "Date/time properties" in the  SARIF spec for the required format.
       */
      endTime?: string;
      /**
       * The process exit code.
       */
      exitCode?: number;
      /**
       * A list of runtime conditions detected by the tool in the course of the analysis.
       */
      toolNotifications?: Notification[];
      /**
       * A list of conditions detected by the tool that are relevant to the tool's configuration.
       */
      configurationNotifications?: Notification[];
      /**
       * The reason for the process exit.
       */
      exitCodeDescription?: string;
      /**
       * The name of the signal that caused the process to exit.
       */
      exitSignalName?: string;
      /**
       * The numeric value of the signal that caused the process to exit.
       */
      exitSignalNumber?: number;
      /**
       * The reason given by the operating system that the process failed to start.
       */
      processStartFailureMessage?: string;
      /**
       * A value indicating whether the tool's execution completed successfully.
       */
      toolExecutionSuccessful?: boolean;
      /**
       * The machine that hosted the analysis tool run.
       */
      machine?: string;
      /**
       * The account that ran the analysis tool.
       */
      account?: string;
      /**
       * The process id for the analysis tool run.
       */
      processId?: number;
      /**
       * An absolute URI specifying the location of the analysis tool's executable.
       */
      executableLocation?: {
        /**
         * A string containing a valid relative or absolute URI.
         */
        uri: string;
        /**
         * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
         */
        uriBaseId?: string;
      };
      /**
       * The working directory for the analysis rool run.
       */
      workingDirectory?: string;
      /**
       * The environment variables associated with the analysis tool process, expressed as key/value pairs.
       */
      environmentVariables?: {
        [k: string]: any;
      };
      /**
       * A file containing the standard input stream to the process that was invoked.
       */
      stdin?: {
        /**
         * A string containing a valid relative or absolute URI.
         */
        uri: string;
        /**
         * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
         */
        uriBaseId?: string;
      };
      /**
       * A file containing the standard output stream from the process that was invoked.
       */
      stdout?: {
        /**
         * A string containing a valid relative or absolute URI.
         */
        uri: string;
        /**
         * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
         */
        uriBaseId?: string;
      };
      /**
       * A file containing the standard error stream from the process that was invoked.
       */
      stderr?: {
        /**
         * A string containing a valid relative or absolute URI.
         */
        uri: string;
        /**
         * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
         */
        uriBaseId?: string;
      };
      /**
       * A file containing the interleaved standard output and standard error stream from the process that was invoked.
       */
      stdoutStderr?: {
        /**
         * A string containing a valid relative or absolute URI.
         */
        uri: string;
        /**
         * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
         */
        uriBaseId?: string;
      };
      /**
       * Key/value pairs that provide additional information about the run.
       */
      properties?: {
        /**
         * A set of distinct strings that provide additional information.
         */
        tags?: string[];
        [k: string]: any;
      };
    };
    /**
     * The location of the analysis tool's log file.
     */
    analysisToolLogFileLocation?: {
      /**
       * A string containing a valid relative or absolute URI.
       */
      uri: string;
      /**
       * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
       */
      uriBaseId?: string;
    };
  };
  /**
   * The absolute URI specified by each uriBaseId symbol on the machine where the tool originally ran.
   */
  originalUriBaseIds?: {
    [k: string]: string;
  };
  /**
   * A dictionary each of whose keys is a URI and each of whose values is a file object.
   */
  files?: {
    [k: string]: File;
  };
  /**
   * A dictionary, each of whose keys specifies a logical location such as a namespace, type or function.
   */
  logicalLocations?: {
    [k: string]: LogicalLocation;
  };
  /**
   * The set of results contained in an SARIF log. The results array can be omitted when a run is solely exporting rules metadata. It must be present (but may be empty) in the event that a log file represents an actual scan.
   */
  results?: Result[];
  /**
   * Items that can be localized, such as message strings and rule metadata.
   */
  resources?: {
    /**
     * A dictionary, each of whose keys is a resource identifier and each of whose values is a localized string.
     */
    messageStrings?: {
      [k: string]: string;
    };
    /**
     * A dictionary, each of whose keys is a string and each of whose values is a 'rule' object, that describe all rules associated with an analysis tool or a specific run of an analysis tool.
     */
    rules?: {
      [k: string]: Rule;
    };
    [k: string]: any;
  };
  /**
   * An identifier for the run.
   */
  id?: string;
  /**
   * A stable identifier for a run, for example, 'nightly Clang analyzer run'. Multiple runs of the same type can have the same stableId.
   */
  stableId?: string;
  /**
   * A global identifier that allows the run to be correlated with other artifacts produced by a larger automation process.
   */
  automationId?: string;
  /**
   * The 'id' property of a separate (potentially external) SARIF 'run' instance that comprises the baseline that was used to compute result 'baselineState' properties for the run.
   */
  baselineId?: string;
  /**
   * The hardware architecture for which the run was targeted.
   */
  architecture?: string;
  /**
   * The MIME type of all rich text message properties in the run. Default: "text/markdown;variant=GFM"
   */
  richMessageMimeType?: string;
  /**
   * The string used to replace sensitive information in a redaction-aware property.
   */
  redactionToken?: string;
  /**
   * Key/value pairs that provide additional information about the run.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information about the run.
     */
    tags?: string[];
    [k: string]: any;
  };
}
/**
 * The runtime environment of the analysis tool run.
 */
export interface Invocation {
  /**
   * A set of files relevant to the invocation of the tool.
   */
  attachments?: Attachment[];
  /**
   * The command line used to invoke the tool.
   */
  commandLine?: string;
  /**
   * An array of strings, containing in order the command line arguments passed to the tool from the operating system.
   */
  arguments?: string[];
  /**
   * The locations of any response files specified on the tool's command line.
   */
  responseFiles?: FileLocation[];
  /**
   * The date and time at which the run started. See "Date/time properties" in the SARIF spec for the required format.
   */
  startTime?: string;
  /**
   * The date and time at which the run ended. See "Date/time properties" in the  SARIF spec for the required format.
   */
  endTime?: string;
  /**
   * The process exit code.
   */
  exitCode?: number;
  /**
   * A list of runtime conditions detected by the tool in the course of the analysis.
   */
  toolNotifications?: Notification[];
  /**
   * A list of conditions detected by the tool that are relevant to the tool's configuration.
   */
  configurationNotifications?: Notification[];
  /**
   * The reason for the process exit.
   */
  exitCodeDescription?: string;
  /**
   * The name of the signal that caused the process to exit.
   */
  exitSignalName?: string;
  /**
   * The numeric value of the signal that caused the process to exit.
   */
  exitSignalNumber?: number;
  /**
   * The reason given by the operating system that the process failed to start.
   */
  processStartFailureMessage?: string;
  /**
   * A value indicating whether the tool's execution completed successfully.
   */
  toolExecutionSuccessful?: boolean;
  /**
   * The machine that hosted the analysis tool run.
   */
  machine?: string;
  /**
   * The account that ran the analysis tool.
   */
  account?: string;
  /**
   * The process id for the analysis tool run.
   */
  processId?: number;
  /**
   * An absolute URI specifying the location of the analysis tool's executable.
   */
  executableLocation?: {
    /**
     * A string containing a valid relative or absolute URI.
     */
    uri: string;
    /**
     * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
     */
    uriBaseId?: string;
  };
  /**
   * The working directory for the analysis rool run.
   */
  workingDirectory?: string;
  /**
   * The environment variables associated with the analysis tool process, expressed as key/value pairs.
   */
  environmentVariables?: {
    [k: string]: any;
  };
  /**
   * A file containing the standard input stream to the process that was invoked.
   */
  stdin?: {
    /**
     * A string containing a valid relative or absolute URI.
     */
    uri: string;
    /**
     * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
     */
    uriBaseId?: string;
  };
  /**
   * A file containing the standard output stream from the process that was invoked.
   */
  stdout?: {
    /**
     * A string containing a valid relative or absolute URI.
     */
    uri: string;
    /**
     * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
     */
    uriBaseId?: string;
  };
  /**
   * A file containing the standard error stream from the process that was invoked.
   */
  stderr?: {
    /**
     * A string containing a valid relative or absolute URI.
     */
    uri: string;
    /**
     * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
     */
    uriBaseId?: string;
  };
  /**
   * A file containing the interleaved standard output and standard error stream from the process that was invoked.
   */
  stdoutStderr?: {
    /**
     * A string containing a valid relative or absolute URI.
     */
    uri: string;
    /**
     * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
     */
    uriBaseId?: string;
  };
  /**
   * Key/value pairs that provide additional information about the run.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
}
/**
 * A file relevant to a tool invocation or to a result.
 */
export interface Attachment {
  /**
   * A message describing the role played by the attachment.
   */
  description?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * The location of the attachment.
   */
  fileLocation: {
    /**
     * A string containing a valid relative or absolute URI.
     */
    uri: string;
    /**
     * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
     */
    uriBaseId?: string;
  };
  [k: string]: any;
}
/**
 * Specifies the location of a file.
 */
export interface FileLocation {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
}
/**
 * Describes a condition relevant to the tool itself, as opposed to being relevant to a target being analyzed by the tool.
 */
export interface Notification {
  /**
   * An identifier for the condition that was encountered.
   */
  id?: string;
  /**
   * The stable, unique identifier of the rule (if any) to which this notification is relevant. If 'ruleKey' is not specified, this member can be used to retrieve rule metadata from the rules dictionary, if it exists.
   */
  ruleId?: string;
  /**
   * A key used to retrieve the rule metadata from the rules dictionary that is relevant to the notificationn.
   */
  ruleKey?: string;
  /**
   * The file and region relevant to this notification.
   */
  physicalLocation?: {
    /**
     * Value that distinguishes this physical location from all other physical locations in this run object.
     */
    id?: number;
    /**
     * The location of the file.
     */
    fileLocation?: {
      /**
       * A string containing a valid relative or absolute URI.
       */
      uri: string;
      /**
       * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
       */
      uriBaseId?: string;
    };
    /**
     * The region within the file where the result was detected.
     */
    region?: {
      /**
       * The line number of the first character in the region.
       */
      startLine?: number;
      /**
       * The column number of the first character in the region.
       */
      startColumn?: number;
      /**
       * The line number of the last character in the region.
       */
      endLine?: number;
      /**
       * The column number of the last character in the region.
       */
      endColumn?: number;
      /**
       * The zero-based offset from the beginning of the file of the first byte or character in the region.
       */
      offset?: number;
      /**
       * The length of the region in bytes or characters.
       */
      length?: number;
      /**
       * The portion of the file contents within the specified region.
       */
      snippet?: {
        /**
         * UTF-8-encoded content from a text file.
         */
        text?: string;
        /**
         * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
         */
        binary?: string;
      };
    };
    /**
     * Specifies a portion of the file that encloses the region. Allows a viewer to display additional context around the region.
     */
    contextRegion?: {
      /**
       * The line number of the first character in the region.
       */
      startLine?: number;
      /**
       * The column number of the first character in the region.
       */
      startColumn?: number;
      /**
       * The line number of the last character in the region.
       */
      endLine?: number;
      /**
       * The column number of the last character in the region.
       */
      endColumn?: number;
      /**
       * The zero-based offset from the beginning of the file of the first byte or character in the region.
       */
      offset?: number;
      /**
       * The length of the region in bytes or characters.
       */
      length?: number;
      /**
       * The portion of the file contents within the specified region.
       */
      snippet?: {
        /**
         * UTF-8-encoded content from a text file.
         */
        text?: string;
        /**
         * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
         */
        binary?: string;
      };
    };
  };
  /**
   * A message that describes the condition that was encountered.
   */
  message: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * A value specifying the severity level of the notification.
   */
  level?: "note" | "warning" | "error";
  /**
   * The thread identifier of the code that generated the notification.
   */
  threadId?: number;
  /**
   * The date and time at which the analysis tool generated the notification.
   */
  time?: string;
  /**
   * The runtime exception, if any, relevant to this notification.
   */
  exception?: {
    /**
     * A string that identifies the kind of exception, for example, the fully qualified type name of an object that was thrown, or the symbolic name of a signal.
     */
    kind?: string;
    /**
     * A plain text message that describes the exception.
     */
    message?: string;
    /**
     * The sequence of function calls leading to the exception.
     */
    stack?: {
      /**
       * A message relevant to this call stack.
       */
      message?: {
        /**
         * A plain text message string.
         */
        text?: string;
        /**
         * The resource id for a plain text message string.
         */
        messageId?: string;
        /**
         * A rich text message string.
         */
        richText?: string;
        /**
         * The resource id for a rich text message string.
         */
        richMessageId?: string;
        /**
         * An array of strings to substitute into the message string.
         */
        arguments?: string[];
      };
      /**
       * An array of stack frames that represent a sequence of calls, rendered in reverse chronological order, that comprise the call stack.
       */
      frames: StackFrame[];
      /**
       * Key/value pairs that provide additional information about the stack.
       */
      properties?: {
        /**
         * A set of distinct strings that provide additional information.
         */
        tags?: string[];
        [k: string]: any;
      };
    };
    /**
     * An array of exception objects each of which is considered a cause of this exception.
     */
    innerExceptions?: Exception[];
    [k: string]: any;
  };
  /**
   * Key/value pairs that provide additional information about the notification.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
}
/**
 * A function call within a stack trace.
 */
export interface StackFrame {
  /**
   * The location to which this stack frame refers.
   */
  location?: {
    /**
     * Identifies the file where the analysis tool produced the result.
     */
    physicalLocation?: {
      /**
       * Value that distinguishes this physical location from all other physical locations in this run object.
       */
      id?: number;
      /**
       * The location of the file.
       */
      fileLocation?: {
        /**
         * A string containing a valid relative or absolute URI.
         */
        uri: string;
        /**
         * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
         */
        uriBaseId?: string;
      };
      /**
       * The region within the file where the result was detected.
       */
      region?: {
        /**
         * The line number of the first character in the region.
         */
        startLine?: number;
        /**
         * The column number of the first character in the region.
         */
        startColumn?: number;
        /**
         * The line number of the last character in the region.
         */
        endLine?: number;
        /**
         * The column number of the last character in the region.
         */
        endColumn?: number;
        /**
         * The zero-based offset from the beginning of the file of the first byte or character in the region.
         */
        offset?: number;
        /**
         * The length of the region in bytes or characters.
         */
        length?: number;
        /**
         * The portion of the file contents within the specified region.
         */
        snippet?: {
          /**
           * UTF-8-encoded content from a text file.
           */
          text?: string;
          /**
           * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
           */
          binary?: string;
        };
      };
      /**
       * Specifies a portion of the file that encloses the region. Allows a viewer to display additional context around the region.
       */
      contextRegion?: {
        /**
         * The line number of the first character in the region.
         */
        startLine?: number;
        /**
         * The column number of the first character in the region.
         */
        startColumn?: number;
        /**
         * The line number of the last character in the region.
         */
        endLine?: number;
        /**
         * The column number of the last character in the region.
         */
        endColumn?: number;
        /**
         * The zero-based offset from the beginning of the file of the first byte or character in the region.
         */
        offset?: number;
        /**
         * The length of the region in bytes or characters.
         */
        length?: number;
        /**
         * The portion of the file contents within the specified region.
         */
        snippet?: {
          /**
           * UTF-8-encoded content from a text file.
           */
          text?: string;
          /**
           * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
           */
          binary?: string;
        };
      };
    };
    /**
     * The human-readable fully qualified name of the logical location where the analysis tool produced the result. If 'logicalLocationKey' is not specified, this member is can used to retrieve the location logicalLocation from the logicalLocations dictionary, if one exists.
     */
    fullyQualifiedLogicalName?: string;
    /**
     * A key used to retrieve the location logicalLocation from the logicalLocations dictionary, when the string specified by 'fullyQualifiedLogicalName' is not unique.
     */
    logicalLocationKey?: string;
    /**
     * The machine-readable fully qualified name for the logical location where the analysis tool produced the result, such as the mangled function name provided by a C++ compiler that encodes calling convention, return type and other details along with the function name.
     */
    decoratedName?: string;
    /**
     * A message relevant to the location.
     */
    message?: {
      /**
       * A plain text message string.
       */
      text?: string;
      /**
       * The resource id for a plain text message string.
       */
      messageId?: string;
      /**
       * A rich text message string.
       */
      richText?: string;
      /**
       * The resource id for a rich text message string.
       */
      richMessageId?: string;
      /**
       * An array of strings to substitute into the message string.
       */
      arguments?: string[];
    };
    /**
     * A set of messages relevant to portions of the location.
     */
    annotations?: Annotation[];
    /**
     * Key/value pairs that provide additional information about the location.
     */
    properties?: {
      /**
       * A set of distinct strings that provide additional information.
       */
      tags?: string[];
      [k: string]: any;
    };
  };
  /**
   * The name of the module that contains the code of this stack frame.
   */
  module?: string;
  /**
   * The thread identifier of the stack frame.
   */
  threadId?: number;
  /**
   * The address of the method or function that is executing.
   */
  address?: number;
  /**
   * The offset from the method or function that is executing.
   */
  offset?: number;
  /**
   * The parameters of the call that is executing.
   */
  parameters?: string[];
  /**
   * Key/value pairs that provide additional information about the stack frame.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
}
export interface Annotation {
  /**
   * A message relevant to the set of locations specified by this annotation.
   */
  message: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * An array of 'physicalLocation' objects associated with this annotation.
   */
  locations: PhysicalLocation[];
  [k: string]: any;
}
/**
 * A physical location relevant to a result. Specifies a reference to a programming artifact together with a range of bytes or characters within that artifact.
 */
export interface PhysicalLocation {
  /**
   * Value that distinguishes this physical location from all other physical locations in this run object.
   */
  id?: number;
  /**
   * The location of the file.
   */
  fileLocation?: {
    /**
     * A string containing a valid relative or absolute URI.
     */
    uri: string;
    /**
     * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
     */
    uriBaseId?: string;
  };
  /**
   * The region within the file where the result was detected.
   */
  region?: {
    /**
     * The line number of the first character in the region.
     */
    startLine?: number;
    /**
     * The column number of the first character in the region.
     */
    startColumn?: number;
    /**
     * The line number of the last character in the region.
     */
    endLine?: number;
    /**
     * The column number of the last character in the region.
     */
    endColumn?: number;
    /**
     * The zero-based offset from the beginning of the file of the first byte or character in the region.
     */
    offset?: number;
    /**
     * The length of the region in bytes or characters.
     */
    length?: number;
    /**
     * The portion of the file contents within the specified region.
     */
    snippet?: {
      /**
       * UTF-8-encoded content from a text file.
       */
      text?: string;
      /**
       * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
       */
      binary?: string;
    };
  };
  /**
   * Specifies a portion of the file that encloses the region. Allows a viewer to display additional context around the region.
   */
  contextRegion?: {
    /**
     * The line number of the first character in the region.
     */
    startLine?: number;
    /**
     * The column number of the first character in the region.
     */
    startColumn?: number;
    /**
     * The line number of the last character in the region.
     */
    endLine?: number;
    /**
     * The column number of the last character in the region.
     */
    endColumn?: number;
    /**
     * The zero-based offset from the beginning of the file of the first byte or character in the region.
     */
    offset?: number;
    /**
     * The length of the region in bytes or characters.
     */
    length?: number;
    /**
     * The portion of the file contents within the specified region.
     */
    snippet?: {
      /**
       * UTF-8-encoded content from a text file.
       */
      text?: string;
      /**
       * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
       */
      binary?: string;
    };
  };
}
export interface Exception {
  /**
   * A string that identifies the kind of exception, for example, the fully qualified type name of an object that was thrown, or the symbolic name of a signal.
   */
  kind?: string;
  /**
   * A plain text message that describes the exception.
   */
  message?: string;
  /**
   * The sequence of function calls leading to the exception.
   */
  stack?: {
    /**
     * A message relevant to this call stack.
     */
    message?: {
      /**
       * A plain text message string.
       */
      text?: string;
      /**
       * The resource id for a plain text message string.
       */
      messageId?: string;
      /**
       * A rich text message string.
       */
      richText?: string;
      /**
       * The resource id for a rich text message string.
       */
      richMessageId?: string;
      /**
       * An array of strings to substitute into the message string.
       */
      arguments?: string[];
    };
    /**
     * An array of stack frames that represent a sequence of calls, rendered in reverse chronological order, that comprise the call stack.
     */
    frames: StackFrame[];
    /**
     * Key/value pairs that provide additional information about the stack.
     */
    properties?: {
      /**
       * A set of distinct strings that provide additional information.
       */
      tags?: string[];
      [k: string]: any;
    };
  };
  /**
   * An array of exception objects each of which is considered a cause of this exception.
   */
  innerExceptions?: Exception[];
  [k: string]: any;
}
/**
 * A single file. In some cases, this file might be nested within another file.
 */
export interface File {
  /**
   * The location of the file.
   */
  fileLocation?: {
    /**
     * A string containing a valid relative or absolute URI.
     */
    uri: string;
    /**
     * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
     */
    uriBaseId?: string;
  };
  /**
   * Identifies the key of the immediate parent of the file, if this file is nested.
   */
  parentKey?: string;
  /**
   * The offset in bytes of the file within its containing file.
   */
  offset?: number;
  /**
   * The length of the file in bytes.
   */
  length?: number;
  /**
   * The MIME type (RFC 2045) of the file.
   */
  mimeType?: string;
  /**
   * The contents of the file, expressed as a MIME Base64-encoded byte sequence.
   */
  contents?: {
    /**
     * UTF-8-encoded content from a text file.
     */
    text?: string;
    /**
     * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
     */
    binary?: string;
  };
  /**
   * An array of hash objects, each of which specifies a hashed value for the file, along with the name of the algorithm used to compute the hash.
   */
  hashes?: Hash[];
  /**
   * Key/value pairs that provide additional information about the file.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
}
/**
 * A hash value of some file or collection of files, together with the algorithm used to compute the hash.
 */
export interface Hash {
  /**
   * The hash value of some file or collection of files, computed by the algorithm named in the 'algorithm' property.
   */
  value: string;
  /**
   * The name of the algorithm used to compute the hash value specified in the 'value' property.
   */
  algorithm:
    | "authentihash"
    | "blake256"
    | "blake512"
    | "ecoh"
    | "fsb"
    | "gost"
    | "groestl"
    | "has160"
    | "haval"
    | "jh"
    | "md2"
    | "md4"
    | "md5"
    | "md6"
    | "radioGatun"
    | "ripeMD"
    | "ripeMD128"
    | "ripeMD160"
    | "ripeMD320"
    | "sdhash"
    | "sha1"
    | "sha224"
    | "sha256"
    | "sha384"
    | "sha512"
    | "sha3"
    | "skein"
    | "snefru"
    | "spectralHash"
    | "ssdeep"
    | "swifft"
    | "tiger"
    | "tlsh"
    | "whirlpool";
}
/**
 * A logical location of a construct that produced a result.
 */
export interface LogicalLocation {
  /**
   * Identifies the construct in which the result occurred. For example, this property might contain the name of a class or a method.
   */
  name?: string;
  /**
   * Identifies the key of the immediate parent of the construct in which the result was detected. For example, this property might point to a logical location that represents the namespace that holds a type.
   */
  parentKey?: string;
  /**
   * The type of construct this logicalLocationComponent refers to. Should be one of 'function', 'member', 'module', 'namespace', 'package', 'resource', or 'type', if any of those accurately describe the construct.
   */
  kind?: string;
}
/**
 * A result produced by an analysis tool.
 */
export interface Result {
  /**
   * The stable, unique identifier of the rule (if any) to which this notification is relevant. If 'ruleKey' is not specified, this member can be used to retrieve rule metadata from the rules dictionary, if it exists.
   */
  ruleId?: string;
  /**
   * A key used to retrieve the rule metadata from the rules dictionary that is relevant to the notificationn.
   */
  ruleKey?: string;
  /**
   * A value specifying the severity level of the result. If this property is not present, its implied value is 'warning'.
   */
  level?: "notApplicable" | "pass" | "note" | "warning" | "error" | "open";
  /**
   * A message that describes the result. The first sentence of the message only will be displayed when visible space is limited.
   */
  message?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * A string that identifies the message within the metadata for the rule used in this result.
   */
  ruleMessageId?: string;
  /**
   * Identifies the file that the analysis tool was instructed to scan. This need not be the same as the file where the result actually occurred.
   */
  analysisTarget?: {
    /**
     * A string containing a valid relative or absolute URI.
     */
    uri: string;
    /**
     * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
     */
    uriBaseId?: string;
  };
  /**
   * One or more locations where the result occurred. Specify only one location unless the problem indicated by the result can only be corrected by making a change at every specified location.
   */
  locations?: Location[];
  /**
   * A unique identifer for the result.
   */
  id?: string;
  /**
   * A set of strings that contribute to the unique identity of the result.
   */
  toolFingerprintContributions?: {
    [k: string]: string;
  };
  /**
   * An array of 'stack' objects relevant to the result.
   */
  stacks?: Stack[];
  /**
   * An array of 'codeFlow' objects relevant to the result.
   */
  codeFlows?: CodeFlow[];
  /**
   * A set of locations relevant to this result.
   */
  relatedLocations?: Location[];
  suppressionStates?: ("suppressedInSource" | "suppressedExternally")[];
  /**
   * A set of files relevant to the result.
   */
  attachments?: Attachment[];
  /**
   * The state of a result relative to a baseline of a previous run.
   */
  baselineState?: "new" | "existing" | "absent";
  /**
   * An array of analysisToolLogFileContents objects which specify the portions of an analysis tool's output that a converter transformed into the result object.
   */
  conversionProvenance?: PhysicalLocation[];
  /**
   * An array of 'fix' objects, each of which represents a proposed fix to the problem indicated by the result.
   */
  fixes?: Fix[];
  /**
   * Key/value pairs that provide additional information about the result.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
}
/**
 * The location where an analysis tool produced a result.
 */
export interface Location {
  /**
   * Identifies the file where the analysis tool produced the result.
   */
  physicalLocation?: {
    /**
     * Value that distinguishes this physical location from all other physical locations in this run object.
     */
    id?: number;
    /**
     * The location of the file.
     */
    fileLocation?: {
      /**
       * A string containing a valid relative or absolute URI.
       */
      uri: string;
      /**
       * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
       */
      uriBaseId?: string;
    };
    /**
     * The region within the file where the result was detected.
     */
    region?: {
      /**
       * The line number of the first character in the region.
       */
      startLine?: number;
      /**
       * The column number of the first character in the region.
       */
      startColumn?: number;
      /**
       * The line number of the last character in the region.
       */
      endLine?: number;
      /**
       * The column number of the last character in the region.
       */
      endColumn?: number;
      /**
       * The zero-based offset from the beginning of the file of the first byte or character in the region.
       */
      offset?: number;
      /**
       * The length of the region in bytes or characters.
       */
      length?: number;
      /**
       * The portion of the file contents within the specified region.
       */
      snippet?: {
        /**
         * UTF-8-encoded content from a text file.
         */
        text?: string;
        /**
         * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
         */
        binary?: string;
      };
    };
    /**
     * Specifies a portion of the file that encloses the region. Allows a viewer to display additional context around the region.
     */
    contextRegion?: {
      /**
       * The line number of the first character in the region.
       */
      startLine?: number;
      /**
       * The column number of the first character in the region.
       */
      startColumn?: number;
      /**
       * The line number of the last character in the region.
       */
      endLine?: number;
      /**
       * The column number of the last character in the region.
       */
      endColumn?: number;
      /**
       * The zero-based offset from the beginning of the file of the first byte or character in the region.
       */
      offset?: number;
      /**
       * The length of the region in bytes or characters.
       */
      length?: number;
      /**
       * The portion of the file contents within the specified region.
       */
      snippet?: {
        /**
         * UTF-8-encoded content from a text file.
         */
        text?: string;
        /**
         * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
         */
        binary?: string;
      };
    };
  };
  /**
   * The human-readable fully qualified name of the logical location where the analysis tool produced the result. If 'logicalLocationKey' is not specified, this member is can used to retrieve the location logicalLocation from the logicalLocations dictionary, if one exists.
   */
  fullyQualifiedLogicalName?: string;
  /**
   * A key used to retrieve the location logicalLocation from the logicalLocations dictionary, when the string specified by 'fullyQualifiedLogicalName' is not unique.
   */
  logicalLocationKey?: string;
  /**
   * The machine-readable fully qualified name for the logical location where the analysis tool produced the result, such as the mangled function name provided by a C++ compiler that encodes calling convention, return type and other details along with the function name.
   */
  decoratedName?: string;
  /**
   * A message relevant to the location.
   */
  message?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * A set of messages relevant to portions of the location.
   */
  annotations?: Annotation[];
  /**
   * Key/value pairs that provide additional information about the location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
}
/**
 * A call stack that is relevant to a result.
 */
export interface Stack {
  /**
   * A message relevant to this call stack.
   */
  message?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * An array of stack frames that represent a sequence of calls, rendered in reverse chronological order, that comprise the call stack.
   */
  frames: StackFrame[];
  /**
   * Key/value pairs that provide additional information about the stack.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
}
/**
 * A set of threadFlows which together describe a pattern of code execution relevant to detecting a result.
 */
export interface CodeFlow {
  /**
   * A message relevant to the code flow.
   */
  message?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * An array of one or more unique threadFlow objects, each of which describes the progress of a program through a thread of execution.
   */
  threadFlows: ThreadFlow[];
  /**
   * Key/value pairs that provide additional information about the code flow.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
}
export interface ThreadFlow {
  /**
   * An string that uniquely identifies the threadFlow within the codeFlow in which it occurs.
   */
  id?: string;
  /**
   * A message relevant to the code flow.
   */
  message?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * An array of 'codeFlowLocation' objects, each of which describes a single location visited by the tool in the course of producing the result.
   */
  locations: CodeFlowLocation[];
  /**
   * Key/value pairs that provide additional information about the code flow.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
  [k: string]: any;
}
/**
 * A location visited by an analysis tool in the course of simulating or monitoring the execution of a program.
 */
export interface CodeFlowLocation {
  /**
   * The 0-based sequence number of the location in the code flow within which it occurs.
   */
  step?: number;
  /**
   * The code location.
   */
  location?: {
    /**
     * Identifies the file where the analysis tool produced the result.
     */
    physicalLocation?: {
      /**
       * Value that distinguishes this physical location from all other physical locations in this run object.
       */
      id?: number;
      /**
       * The location of the file.
       */
      fileLocation?: {
        /**
         * A string containing a valid relative or absolute URI.
         */
        uri: string;
        /**
         * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
         */
        uriBaseId?: string;
      };
      /**
       * The region within the file where the result was detected.
       */
      region?: {
        /**
         * The line number of the first character in the region.
         */
        startLine?: number;
        /**
         * The column number of the first character in the region.
         */
        startColumn?: number;
        /**
         * The line number of the last character in the region.
         */
        endLine?: number;
        /**
         * The column number of the last character in the region.
         */
        endColumn?: number;
        /**
         * The zero-based offset from the beginning of the file of the first byte or character in the region.
         */
        offset?: number;
        /**
         * The length of the region in bytes or characters.
         */
        length?: number;
        /**
         * The portion of the file contents within the specified region.
         */
        snippet?: {
          /**
           * UTF-8-encoded content from a text file.
           */
          text?: string;
          /**
           * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
           */
          binary?: string;
        };
      };
      /**
       * Specifies a portion of the file that encloses the region. Allows a viewer to display additional context around the region.
       */
      contextRegion?: {
        /**
         * The line number of the first character in the region.
         */
        startLine?: number;
        /**
         * The column number of the first character in the region.
         */
        startColumn?: number;
        /**
         * The line number of the last character in the region.
         */
        endLine?: number;
        /**
         * The column number of the last character in the region.
         */
        endColumn?: number;
        /**
         * The zero-based offset from the beginning of the file of the first byte or character in the region.
         */
        offset?: number;
        /**
         * The length of the region in bytes or characters.
         */
        length?: number;
        /**
         * The portion of the file contents within the specified region.
         */
        snippet?: {
          /**
           * UTF-8-encoded content from a text file.
           */
          text?: string;
          /**
           * MIME Base64-encoded content from a binary file, or from a text file in its original encoding.
           */
          binary?: string;
        };
      };
    };
    /**
     * The human-readable fully qualified name of the logical location where the analysis tool produced the result. If 'logicalLocationKey' is not specified, this member is can used to retrieve the location logicalLocation from the logicalLocations dictionary, if one exists.
     */
    fullyQualifiedLogicalName?: string;
    /**
     * A key used to retrieve the location logicalLocation from the logicalLocations dictionary, when the string specified by 'fullyQualifiedLogicalName' is not unique.
     */
    logicalLocationKey?: string;
    /**
     * The machine-readable fully qualified name for the logical location where the analysis tool produced the result, such as the mangled function name provided by a C++ compiler that encodes calling convention, return type and other details along with the function name.
     */
    decoratedName?: string;
    /**
     * A message relevant to the location.
     */
    message?: {
      /**
       * A plain text message string.
       */
      text?: string;
      /**
       * The resource id for a plain text message string.
       */
      messageId?: string;
      /**
       * A rich text message string.
       */
      richText?: string;
      /**
       * The resource id for a rich text message string.
       */
      richMessageId?: string;
      /**
       * An array of strings to substitute into the message string.
       */
      arguments?: string[];
    };
    /**
     * A set of messages relevant to portions of the location.
     */
    annotations?: Annotation[];
    /**
     * Key/value pairs that provide additional information about the location.
     */
    properties?: {
      /**
       * A set of distinct strings that provide additional information.
       */
      tags?: string[];
      [k: string]: any;
    };
  };
  /**
   * The name of the module that contains the code that is executing.
   */
  module?: string;
  /**
   * A dictionary, each of whose keys specifies a variable or expression, the associated value of which represents the variable or expression value. For an annotation of kind 'continuation', for example, this dictionary might hold the current assumed values of a set of global variables.
   */
  state?: {
    [k: string]: any;
  };
  /**
   * An integer representing a containment hierarchy within the thread flow
   */
  nestingLevel?: number;
  /**
   * An integer representing the temporal order in which execution reached this location.
   */
  executionOrder?: number;
  /**
   * Specifies the importance of this location in understanding the code flow in which it occurs. The order from most to least important is "essential", "important", "unimportant". Default: "important".
   */
  importance?: "important" | "essential" | "unimportant";
  /**
   * Key/value pairs that provide additional information about the code location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
}
/**
 * A proposed fix for the problem represented by a result object. A fix specifies a set of file to modify. For each file, it specifies a set of bytes to remove, and provides a set of new bytes to replace them.
 */
export interface Fix {
  /**
   * A message that describes the proposed fix, enabling viewers to present the proposed change to an end user.
   */
  description?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * One or more file changes that comprise a fix for a result.
   */
  fileChanges: FileChange[];
}
/**
 * A change to a single file.
 */
export interface FileChange {
  /**
   * The location of the file to change.
   */
  fileLocation?: {
    /**
     * A string containing a valid relative or absolute URI.
     */
    uri: string;
    /**
     * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
     */
    uriBaseId?: string;
  };
  /**
   * An array of replacement objects, each of which represents the replacement of a single range of bytes in a single file specified by 'fileLocation'.
   */
  replacements: Replacement[];
}
/**
 * The replacement of a single range of bytes in a file. Specifies the location within the file where the replacement is to be made, the number of bytes to remove at that location, and a sequence of bytes to insert at that location.
 */
export interface Replacement {
  /**
   * A non-negative integer specifying the offset in bytes from the beginning of the file at which bytes are to be removed, inserted or both. An offset of 0 shall denote the first byte in the file.
   */
  offset: number;
  /**
   * The number of bytes to delete, starting at the byte offset specified by offset, measured from the beginning of the file.
   */
  deletedLength?: number;
  /**
   * The MIME Base64-encoded byte sequence to be inserted at the byte offset specified by the 'offset' property, measured from the beginning of the file.
   */
  insertedBytes?: string;
}
/**
 * Describes an analysis rule.
 */
export interface Rule {
  /**
   * A stable, opaque identifier for the rule.
   */
  id: string;
  /**
   * A rule identifier that is understandable to an end user.
   */
  name?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * A concise description of the rule. Should be a single sentence that is understandable when visible space is limited to a single line of text.
   */
  shortDescription?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * A description of the rule. Should, as far as possible, provide details sufficient to enable resolution of any problem indicated by the result.
   */
  fullDescription?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * A set of name/value pairs with arbitrary names. The value within each name/value pair consists of plain text interspersed with placeholders, which can be used to construct a message in combination with an arbitrary number of additional string arguments.
   */
  messageStrings?: {
    [k: string]: string;
  };
  /**
   * A set of name/value pairs with arbitrary names. The value within each name/value pair consists of rich text interspersed with placeholders, which can be used to construct a message in combination with an arbitrary number of additional string arguments.
   */
  richMessageStrings?: {
    [k: string]: string;
  };
  /**
   * Information about the rule that can be configured at runtime.
   */
  configuration?: {
    /**
     * Specifies whether the rule will be evaluated during the scan.
     */
    enabled?: boolean;
    /**
     * Specifies the default severity level of the result.
     */
    defaultLevel?: "note" | "warning" | "error" | "open";
    /**
     * Contains configuration information specific to this rule.
     */
    parameters?: {
      /**
       * A set of distinct strings that provide additional configuration information.
       */
      tags?: string[];
      [k: string]: any;
    };
  };
  /**
   * A URI where the primary documentation for the rule can be found.
   */
  helpLocation?: string;
  /**
   * Provides the primary documentation for the rule, useful when there is no online documentation.
   */
  help?: {
    /**
     * A plain text message string.
     */
    text?: string;
    /**
     * The resource id for a plain text message string.
     */
    messageId?: string;
    /**
     * A rich text message string.
     */
    richText?: string;
    /**
     * The resource id for a rich text message string.
     */
    richMessageId?: string;
    /**
     * An array of strings to substitute into the message string.
     */
    arguments?: string[];
  };
  /**
   * Key/value pairs that provide additional information about the rule.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     */
    tags?: string[];
    [k: string]: any;
  };
}
