// Copyright (c) Microsoft.  All Rights Reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using FluentAssertions;
using Microsoft.CodeAnalysis.Sarif;
using Xunit;

namespace Microsoft.CodeAnalysis.Test.UnitTests.Sarif.Core
{
    public class ResultTests
    {
        [Fact]
        public void Result_Kind_ResetsLevelValue()
        {
            // This test ensures NotYetAutoGenerated field 'Level' value is reset if 'Kind' value is changed to a non-default value.
            // see .src/sarif/NotYetAutoGenerated/Result.cs (Level property)
            var result = new Result();

            result.Level.Should().Be(FailureLevel.Warning);

            result.Kind = ResultKind.Pass;

            result.Level.Should().Be(FailureLevel.None);
        }

        [Fact]
        public void Result_Level_ResetsKindValue()
        {
            // This test ensures NotYetAutoGenerated field 'Kind' value is reset if 'Level' value is changed to a non-default value.
            // see .src/sarif/NotYetAutoGenerated/Result.cs (Kind property)
            var result = new Result();

            result.Kind.Should().Be(ResultKind.Fail); // Default value

            result.Kind = ResultKind.Pass;

            result.Level = FailureLevel.Error;

            result.Kind.Should().Be(ResultKind.Fail);
        }
    }
}
