<?xml version="1.0" encoding="UTF-8"?>
<DEFECTS>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs373273.cpp</FILENAME>
      <LINE>16</LINE>
      <COLUMN>5</COLUMN>
    </SFA>
    <DEFECTCODE>6385</DEFECTCODE>
    <DESCRIPTION>Reading invalid data from 'data':  the readable size is 'n*4' bytes, but '24' bytes may be read.</DESCRIPTION>
    <FUNCTION>BadFunctionKvtInNewArray</FUNCTION>
    <DECORATED>?BadFunctionKvtInNewArray@@YAHXZ</DECORATED>
    <FUNCLINE>8</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs373273.cpp</FILENAME>
        <LINE>10</LINE>
        <COLUMN>5</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'n' is equal to 5</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs373273.cpp</FILENAME>
        <LINE>11</LINE>
        <COLUMN>5</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is an array of 5 elements (20 bytes)</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs373273.cpp</FILENAME>
        <LINE>12</LINE>
        <COLUMN>9</COLUMN>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs373273.cpp</FILENAME>
        <LINE>14</LINE>
        <COLUMN>5</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>'n' is an In/Out argument to 'new[]' (declared at d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\predefined c++ types (compiler internal):38)</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs373273.cpp</FILENAME>
        <LINE>16</LINE>
        <COLUMN>5</COLUMN>
        <KEYEVENT>
          <ID>4</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>Invalid read from 'data[5]', (readable range is 0 to 4)</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
  <DEFECT>
    <SFA>
      <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
      <FILENAME>tfs373273.cpp</FILENAME>
      <LINE>42</LINE>
      <COLUMN>5</COLUMN>
    </SFA>
    <DEFECTCODE>6385</DEFECTCODE>
    <DESCRIPTION>Reading invalid data from 'data':  the readable size is 'n*4' bytes, but '24' bytes may be read.</DESCRIPTION>
    <FUNCTION>BadFunctionKvtInConstructor</FUNCTION>
    <DECORATED>?BadFunctionKvtInConstructor@@YAHXZ</DECORATED>
    <FUNCLINE>34</FUNCLINE>
    <PROBABILITY>1</PROBABILITY>
    <RANK>4</RANK>
    <CATEGORY>
      <RULECATEGORY>mspft</RULECATEGORY>
    </CATEGORY>
    <PATH>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs373273.cpp</FILENAME>
        <LINE>36</LINE>
        <COLUMN>5</COLUMN>
        <KEYEVENT>
          <ID>1</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'n' is equal to 5</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs373273.cpp</FILENAME>
        <LINE>37</LINE>
        <COLUMN>5</COLUMN>
        <KEYEVENT>
          <ID>2</ID>
          <KIND>declaration</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>'data' is an array of 5 elements (20 bytes)</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs373273.cpp</FILENAME>
        <LINE>38</LINE>
        <COLUMN>9</COLUMN>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs373273.cpp</FILENAME>
        <LINE>40</LINE>
        <COLUMN>13</COLUMN>
        <KEYEVENT>
          <ID>3</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Full</IMPORTANCE>
          <MESSAGE>'n' is an Input to 'SampleClass::{ctor}' (declared on line 28)</MESSAGE>
        </KEYEVENT>
      </SFA>
      <SFA>
        <FILEPATH>d:\src\sarif-sdk\src\sarif.functionaltests\convertertestdata\prefast\src\fixedbugs\</FILEPATH>
        <FILENAME>tfs373273.cpp</FILENAME>
        <LINE>42</LINE>
        <COLUMN>5</COLUMN>
        <KEYEVENT>
          <ID>4</ID>
          <KIND>usage</KIND>
          <IMPORTANCE>Essential</IMPORTANCE>
          <MESSAGE>Invalid read from 'data[5]', (readable range is 0 to 4)</MESSAGE>
        </KEYEVENT>
      </SFA>
    </PATH>
  </DEFECT>
</DEFECTS>