// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;

using Newtonsoft.Json;

namespace Microsoft.CodeAnalysis.Sarif.Taxonomies
{
    /// <summary>
    /// Provides the id → name map of every MITRE CWE <em>Category</em> (e.g. <c>CWE-16</c>
    /// "Configuration"). A Category is an organizational grouping of weaknesses, never a valid
    /// <c>result.ruleId</c> mapping target; naming one in place of the specific Weakness under it
    /// is the single most common mis-mapping an AI producer makes.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This map exists for one purpose: to let a consumer <em>recognize and explain</em> that
    /// class of mistake. The authoritative test of "is this a valid mapping target" is
    /// <see cref="CweTaxonomy.IsKnownWeakness(string)"/> (sound and complete — it also rejects
    /// Views, withdrawn ids, and typos). This map sharpens the resulting diagnostic from a generic
    /// "not a Weakness" into a teaching "<c>CWE-16</c> is the Category 'Configuration'; map to the
    /// specific Weakness it contains."
    /// </para>
    /// <para>
    /// The embedded <c>CweCategories.json</c> is generated by
    /// <c>scripts/generate_cwe_taxonomy.py</c> from the same MITRE catalog, in the same run, as
    /// <c>CweTaxonomy.sarif</c> — so the two never drift in version.
    /// </para>
    /// </remarks>
    public static class CweCategories
    {
        private const string ResourceName = "Microsoft.CodeAnalysis.Sarif.Taxonomies.CweCategories.json";

        private static readonly object Gate = new object();
        private static IReadOnlyDictionary<int, string> categoryNamesByCwe;

        /// <summary>
        /// The full map, keyed by CWE number (e.g. <c>16</c>) to the MITRE Category name
        /// (e.g. <c>"Configuration"</c>).
        /// </summary>
        public static IReadOnlyDictionary<int, string> CategoryNamesByCwe => LoadTable();

        /// <summary>
        /// Determines whether a CWE identifier names a MITRE Category.
        /// </summary>
        /// <param name="cweId">
        /// A CWE identifier in any form the SDK accepts: a canonical id (<c>CWE-16</c>, any case)
        /// or an AI ruleId carrying a sub-id (<c>CWE-16/insecure-default</c>).
        /// </param>
        /// <returns><c>true</c> when the id resolves to a known Category; otherwise <c>false</c>.</returns>
        public static bool IsCategory(string cweId) => TryGetCategoryName(cweId, out _);

        /// <summary>
        /// Looks up the MITRE Category name for a CWE identifier.
        /// </summary>
        /// <param name="cweId">
        /// A CWE identifier in any form the SDK accepts: a canonical id (<c>CWE-16</c>, any case)
        /// or an AI ruleId carrying a sub-id (<c>CWE-16/insecure-default</c>).
        /// </param>
        /// <param name="categoryName">The Category name (e.g. <c>"Configuration"</c>), when found.</param>
        /// <returns><c>true</c> when the id resolves to a known Category; otherwise <c>false</c>.</returns>
        public static bool TryGetCategoryName(string cweId, out string categoryName)
        {
            categoryName = null;
            return CweSecuritySeverity.TryGetCweNumber(cweId, out int cweNumber)
                && LoadTable().TryGetValue(cweNumber, out categoryName);
        }

        private static IReadOnlyDictionary<int, string> LoadTable()
        {
            lock (Gate)
            {
                if (categoryNamesByCwe == null)
                {
                    categoryNamesByCwe = ParseEmbeddedTable();
                }
                return categoryNamesByCwe;
            }
        }

        private static IReadOnlyDictionary<int, string> ParseEmbeddedTable()
        {
            Assembly assembly = typeof(CweCategories).Assembly;
            using Stream stream = assembly.GetManifestResourceStream(ResourceName)
                ?? throw new InvalidOperationException(
                    "Embedded CWE categories resource '" + ResourceName + "' was not found in assembly '"
                    + assembly.FullName + "'.");
            using var reader = new StreamReader(stream, Encoding.UTF8);

            CategoriesDocument document = JsonConvert.DeserializeObject<CategoriesDocument>(reader.ReadToEnd());
            var table = new Dictionary<int, string>(document.Categories.Count);
            foreach (KeyValuePair<string, string> entry in document.Categories)
            {
                if (CweSecuritySeverity.TryGetCweNumber(entry.Key, out int cweNumber))
                {
                    table[cweNumber] = entry.Value;
                }
            }
            return table;
        }

        private sealed class CategoriesDocument
        {
            [JsonProperty("version")]
            public string Version { get; set; }

            [JsonProperty("categories")]
            public Dictionary<string, string> Categories { get; set; }
        }
    }
}
