//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.Sarif.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.Sarif.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the errors of type: Binary with unsupported image type
        ///
        ///
        ///Full Name,Detail Text,Copyright Info,Called Function,Source Location(s)
        ///c:\users\bion\desktop\apiscan\api0000_testing_0.0.0.0_0\temp\x\x64\debug\debuggerextensions\components\arm\dbgeng.dll,MaX detected a binary with unsupported image type &apos;PEARM&apos;.,© Microsoft Corporation. All rights reserved.,,
        ///c:\users\bion\desktop\apiscan\api0000_testing_0.0.0.0_0\temp\x\x64\debug\debuggerextensions\components\arm\dbghelp.dll,MaX detected a binary wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApiScanBinaryWithUnsupportedImageType {
            get {
                return ResourceManager.GetString("ApiScanBinaryWithUnsupportedImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ApiScanBinaryWithUnsupportedImageType_Expected {
            get {
                object obj = ResourceManager.GetObject("ApiScanBinaryWithUnsupportedImageType_Expected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the errors of type: Documentation Not Found
        ///
        ///
        ///Full Name,Detail Text,Called Function,Source Location(s),Platform
        ///Layout\AppVerifierPlugins\Release_Win32\MSECvrf.dll,RtlDeleteCriticalSection is either an internal Platform interface or a call internal to the software set or meta tags correctly associating it with an MSDN.com reference page have not been submitted to MSDN.com by the owning documentation team.,ntdll.dll!RtlDeleteCriticalSection (),d:\bld\20\8\sources\src\appverifierplugins\vfmain.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApiScanDocumentationNotFound {
            get {
                return ResourceManager.GetString("ApiScanDocumentationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ApiScanDocumentationNotFound_Expected {
            get {
                object obj = ResourceManager.GetObject("ApiScanDocumentationNotFound_Expected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ApiScanLogo {
            get {
                object obj = ResourceManager.GetObject("ApiScanLogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the errors of type: Missing Symbols
        ///
        ///
        ///Full Name,Detail Text,Copyright Info,Called Function,Source Location(s)
        ///c:\users\bion\desktop\apiscan\api0000_testing_0.0.0.0_0\temp\x\layout\2\1\asa.exe,The symbols could not be located.,Copyright (C) Microsoft Corporation. All rights reserved.,,
        ///c:\users\bion\desktop\apiscan\api0000_testing_0.0.0.0_0\temp\x\layout\2\1\autorunsc.exe,The symbols could not be located.,Copyright (C) 2002-2009 Mark Russinovich and Bryce Cogswell,,
        ///c:\users\bion\desktop\apis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApiScanMissingSymbols {
            get {
                return ResourceManager.GetString("ApiScanMissingSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ApiScanMissingSymbols_Expected {
            get {
                object obj = ResourceManager.GetObject("ApiScanMissingSymbols_Expected", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
