// Copyright (c) Microsoft.  All Rights Reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Microsoft.CodeAnalysis.Sarif
{
    /// <summary>
    /// Defines methods to support the comparison of objects of type ResultProvenance for sorting.
    /// </summary>
    [GeneratedCode("Microsoft.Json.Schema.ToDotNet", "2.2.0.0")]
    internal sealed class ResultProvenanceComparer : IComparer<ResultProvenance>
    {
        internal static readonly ResultProvenanceComparer Instance = new ResultProvenanceComparer();

        public int Compare(ResultProvenance left, ResultProvenance right)
        {
            int compareResult = 0;

            // TryReferenceCompares is an autogenerated extension method
            // that will properly handle the case when 'left' is null.
            if (left.TryReferenceCompares(right, out compareResult))
            {
                return compareResult;
            }

            compareResult = left.FirstDetectionTimeUtc.CompareTo(right.FirstDetectionTimeUtc);
            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.LastDetectionTimeUtc.CompareTo(right.LastDetectionTimeUtc);
            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.FirstDetectionRunGuid.CompareTo(right.FirstDetectionRunGuid);
            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.LastDetectionRunGuid.CompareTo(right.LastDetectionRunGuid);
            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.InvocationIndex.CompareTo(right.InvocationIndex);
            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.ConversionSources.ListCompares(right.ConversionSources, PhysicalLocationComparer.Instance);
            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.Properties.DictionaryCompares(right.Properties, SerializedPropertyInfoComparer.Instance);
            if (compareResult != 0)
            {
                return compareResult;
            }

            return compareResult;
        }
    }
}