// Copyright (c) Microsoft.  All Rights Reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;
using Microsoft.CodeAnalysis.Sarif.Readers;
using Newtonsoft.Json;

namespace Microsoft.CodeAnalysis.Sarif
{
    /// <summary>
    /// Information about a rule that can be configured at runtime.
    /// </summary>
    [DataContract]
    [GeneratedCode("Microsoft.Json.Schema.ToDotNet", "0.61.0.0")]
    public partial class RuleConfiguration : PropertyBagHolder, ISarifNode
    {
        public static IEqualityComparer<RuleConfiguration> ValueComparer => RuleConfigurationEqualityComparer.Instance;

        public bool ValueEquals(RuleConfiguration other) => ValueComparer.Equals(this, other);
        public int ValueGetHashCode() => ValueComparer.GetHashCode(this);

        /// <summary>
        /// Gets a value indicating the type of object implementing <see cref="ISarifNode" />.
        /// </summary>
        public SarifNodeKind SarifNodeKind
        {
            get
            {
                return SarifNodeKind.RuleConfiguration;
            }
        }

        /// <summary>
        /// Specifies whether the rule will be evaluated during the scan.
        /// </summary>
        [DataMember(Name = "enabled", IsRequired = false, EmitDefaultValue = false)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Specifies the default severity level for results generated by this rule.
        /// </summary>
        [DataMember(Name = "defaultLevel", IsRequired = false, EmitDefaultValue = false)]
        [DefaultValue(RuleConfigurationDefaultLevel.Warning)]
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate)]
        [JsonConverter(typeof(Microsoft.CodeAnalysis.Sarif.Readers.EnumConverter))]
        public RuleConfigurationDefaultLevel DefaultLevel { get; set; }

        /// <summary>
        /// Specifies the default priority or importance for results generated by this rule.
        /// </summary>
        [DataMember(Name = "defaultRank", IsRequired = false, EmitDefaultValue = false)]
        [DefaultValue(0)]
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate)]
        public double DefaultRank { get; set; }

        /// <summary>
        /// Contains configuration information specific to this rule.
        /// </summary>
        [DataMember(Name = "parameters", IsRequired = false, EmitDefaultValue = false)]
        public IDictionary<string, SerializedPropertyInfo> Parameters { get; set; }

        /// <summary>
        /// Key/value pairs that provide additional information about the rule configuration.
        /// </summary>
        [DataMember(Name = "properties", IsRequired = false, EmitDefaultValue = false)]
        internal override IDictionary<string, SerializedPropertyInfo> Properties { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="RuleConfiguration" /> class.
        /// </summary>
        public RuleConfiguration()
        {
            DefaultLevel = RuleConfigurationDefaultLevel.Warning;
            DefaultRank = 0;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RuleConfiguration" /> class from the supplied values.
        /// </summary>
        /// <param name="enabled">
        /// An initialization value for the <see cref="P:Enabled" /> property.
        /// </param>
        /// <param name="defaultLevel">
        /// An initialization value for the <see cref="P:DefaultLevel" /> property.
        /// </param>
        /// <param name="defaultRank">
        /// An initialization value for the <see cref="P:DefaultRank" /> property.
        /// </param>
        /// <param name="parameters">
        /// An initialization value for the <see cref="P:Parameters" /> property.
        /// </param>
        /// <param name="properties">
        /// An initialization value for the <see cref="P:Properties" /> property.
        /// </param>
        public RuleConfiguration(bool enabled, RuleConfigurationDefaultLevel defaultLevel, double defaultRank, IDictionary<string, SerializedPropertyInfo> parameters, IDictionary<string, SerializedPropertyInfo> properties)
        {
            Init(enabled, defaultLevel, defaultRank, parameters, properties);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RuleConfiguration" /> class from the specified instance.
        /// </summary>
        /// <param name="other">
        /// The instance from which the new instance is to be initialized.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if <paramref name="other" /> is null.
        /// </exception>
        public RuleConfiguration(RuleConfiguration other)
        {
            if (other == null)
            {
                throw new ArgumentNullException(nameof(other));
            }

            Init(other.Enabled, other.DefaultLevel, other.DefaultRank, other.Parameters, other.Properties);
        }

        ISarifNode ISarifNode.DeepClone()
        {
            return DeepCloneCore();
        }

        /// <summary>
        /// Creates a deep copy of this instance.
        /// </summary>
        public RuleConfiguration DeepClone()
        {
            return (RuleConfiguration)DeepCloneCore();
        }

        private ISarifNode DeepCloneCore()
        {
            return new RuleConfiguration(this);
        }

        private void Init(bool enabled, RuleConfigurationDefaultLevel defaultLevel, double defaultRank, IDictionary<string, SerializedPropertyInfo> parameters, IDictionary<string, SerializedPropertyInfo> properties)
        {
            Enabled = enabled;
            DefaultLevel = defaultLevel;
            DefaultRank = defaultRank;
            if (parameters != null)
            {
                Parameters = new Dictionary<string, SerializedPropertyInfo>(parameters);
            }

            if (properties != null)
            {
                Properties = new Dictionary<string, SerializedPropertyInfo>(properties);
            }
        }
    }
}