# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

<#
.SYNOPSIS
    Emits GroupingSample.sarif - the deterministic worked sample for the
    two-tier finding-grouping convention (docs/ai/grouping-findings.md).

.DESCRIPTION
    Convention: SARIF samples in this repo are GENERATED by a script and gated
    by a byte-identical regen test, never hand-authored. A hand-authored sample
    is an unverified claim; a generated one is provably the real output of the
    official emit verbs, so anything (human or AI) that learns the shape from it
    learns the true contract. See GroupingGeneratedSampleTests.cs for the gate.

    This sample is the worked example from docs/ai/grouping-findings.md: an
    unauthenticated SSRF assembled from two raw findings.

      runs[0]  ai/origin = generated    two raw findings:
                 results[0] CWE-306/missing-auth-check
                 results[1] CWE-918/unvalidated-fetch
      runs[1]  ai/origin = synthesized  one cluster:
                 results[0] CWE-918/ssrf-via-unvalidated-fetch

    The cluster's primary location 'includes' both raw findings via 'sarif:'
    pointers in its relatedLocations; each raw finding carries the inverse
    'isIncludedBy' pointer back to the cluster. The links are reciprocal by
    construction (AI1015) and flow synthesized -> generated (AI2020); every
    'sarif:' pointer resolves against the final assembled log (SARIF1013).

    Pipeline (the genuine multitool emit chain - no hand-assembly):

      1. emit-run x2     - one staged '.wip.jsonl' per run, each with a rich
                           header (tool.driver, versionControlProvenance mapped
                           to SRCROOT, automationDetails, properties.ai/origin).
      2. emit-results    - each fully-formed Result piped in as JSON, carrying
                           message.markdown, rank, ai/exploitability,
                           ai/attackerPosition, and the grouping cross-links.
      3. emit-finalize   - replays BOTH staged logs into one ORDERED multi-run
           --inputs        SARIF file (runs[i] <- the i-th input), the property
                           cross-run 'sarif:' pointers require. Per-run CWE
                           enrichment, SRCROOT rebasing to the repository blob
                           URL, and text-file embedding all run here.
      4. --validate      - the assembled log is validated under --rule-kind
                           Sarif;AI; the script fails if anything is reported.

    Determinism: all payloads use [ordered] hashtables (stable JSON property
    order), fixed GUIDs / a fixed versionControlProvenance triple, and a
    LF-pinned source file (proxy.ts, pinned in .gitattributes) so the embedded
    contents.text and its sha-256 are identical on every host OS.

.PARAMETER Configuration
    The build configuration whose Sarif.Multitool.dll to drive. Defaults to Release.
#>
param([string]$Configuration = "Release")

$ErrorActionPreference = "Stop"

$sampleDir = $PSScriptRoot
$repoRoot = (Resolve-Path (Join-Path $sampleDir "..\..\..\..")).Path
$multitool = Join-Path $repoRoot "bld/bin/AnyCPU_$Configuration/Sarif.Multitool/net8.0/Sarif.Multitool.dll"
if (-not (Test-Path $multitool)) {
    throw "Sarif.Multitool.dll not found at '$multitool'. Build the SDK in $Configuration first (e.g. dotnet build src\Sarif.Multitool\Sarif.Multitool.csproj -c $Configuration)."
}

# SRCROOT is the sample folder so emit-finalize can read and embed proxy.ts.
# It is rebased to the repository blob URL in the finalized output, so this
# machine-specific local path never reaches the fixture.
$srcRootUri = ([System.Uri]("$sampleDir\")).AbsoluteUri

# A fixed provenance triple keeps the rebased SRCROOT and artifact URLs stable
# across hosts. These coordinates are illustrative; the sample is not a real repo.
$vcp = [ordered]@{
    repositoryUri = 'https://github.com/example/grouping-sample'
    revisionId    = '0000000000000000000000000000000000000000'
    branch        = 'main'
    mappedTo      = [ordered]@{ uriBaseId = 'SRCROOT' }
}

function New-RunHeader([string]$origin, [string]$guid) {
    [ordered]@{
        tool = [ordered]@{ driver = [ordered]@{
            name            = 'GroupingSamplerScanner'
            version         = '0.1.0'
            semanticVersion = '0.1.0'
            informationUri  = 'https://groupingsampler.example.com/'
            organization    = 'Example Scanner Authority'
        } }
        versionControlProvenance = @($vcp)
        originalUriBaseIds = [ordered]@{ SRCROOT = [ordered]@{ uri = $srcRootUri } }
        automationDetails = [ordered]@{ guid = $guid; correlationGuid = '11111111-1111-1111-1111-111111111111' }
        properties = [ordered]@{ 'ai/origin' = $origin }
    }
}

function Invoke-EmitRun([string]$handle, $header) {
    ($header | ConvertTo-Json -Depth 32 -Compress) | & dotnet $multitool emit-run $handle --force-overwrite | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "emit-run failed (exit $LASTEXITCODE)." }
}

function Invoke-EmitResult([string]$handle, $payload) {
    ($payload | ConvertTo-Json -Depth 16 -Compress) | & dotnet $multitool emit-results $handle | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "emit-results failed (exit $LASTEXITCODE)." }
}

# Stage the two runs under TEMP; only the finalized fixture lands in the sample
# folder. emit-run derives the staged log name from the handle ('<handle>.wip.jsonl').
$stageDir = Join-Path ([System.IO.Path]::GetTempPath()) ("grouping-sample-" + [System.Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $stageDir | Out-Null
$genHandle = Join-Path $stageDir 'generated.sarif'
$synHandle = Join-Path $stageDir 'synthesized.sarif'
$outPath = Join-Path $sampleDir 'GroupingSample.sarif'

# emit-run / emit-finalize auto-detect CI pipeline context (GitHub Actions via
# GITHUB_*, Azure DevOps via TF_BUILD) and reconcile provenance against it. This
# sample carries its own deterministic, fictitious versionControlProvenance and
# no pipeline automationDetails, so when the generator runs inside CI the ambient
# coordinates (e.g. GITHUB_REPOSITORY=microsoft/sarif-sdk) conflict with the
# supplied repositoryUri and abort emit-run. Clear the detection gates + identity
# vars for the duration of the emit chain so both detectors return None and the
# fixture stays host-independent.
$ciEnvShield = [ordered]@{
    'TF_BUILD'          = $null
    'GITHUB_ACTIONS'    = $null
    'GITHUB_SERVER_URL' = $null
    'GITHUB_REPOSITORY' = $null
    'GITHUB_SHA'        = $null
    'GITHUB_REF_NAME'   = $null
    'GITHUB_REF'        = $null
}
$savedCiEnv = [ordered]@{}
foreach ($name in $ciEnvShield.Keys) {
    $savedCiEnv[$name] = [System.Environment]::GetEnvironmentVariable($name)
    [System.Environment]::SetEnvironmentVariable($name, $ciEnvShield[$name])
}

try {
    Write-Host "[1/4] emit-run x2 (generated, synthesized)"
    Invoke-EmitRun $genHandle (New-RunHeader 'generated' '22222222-2222-2222-2222-222222222222')
    Invoke-EmitRun $synHandle (New-RunHeader 'synthesized' '33333333-3333-3333-3333-333333333333')

    Write-Host "[2/4] emit-results (2 raw findings + 1 cluster, cross-linked)"

    # runs[0].results[0] - missing auth check; isIncludedBy the cluster (runs[1]/results[0]).
    Invoke-EmitResult $genHandle ([ordered]@{
        ruleId = 'CWE-306/missing-auth-check'
        level  = 'error'
        rank   = 80
        message = [ordered]@{
            text     = 'Missing authentication check on the public proxy ingress.'
            markdown = '**CWE-306** - the public proxy entrypoint performs no authentication, so any remote caller reaches the outbound-fetch path.'
        }
        locations = @([ordered]@{
            id = 0
            physicalLocation = [ordered]@{ artifactLocation = [ordered]@{ uri = 'src/api/proxy.ts'; uriBaseId = 'SRCROOT' }; region = [ordered]@{ startLine = 7 } }
            relationships = @([ordered]@{ target = 1; kinds = @('isIncludedBy') })
        })
        relatedLocations = @([ordered]@{
            id = 1
            physicalLocation = [ordered]@{ artifactLocation = [ordered]@{ uri = 'sarif:/runs/1/results/0' } }
            message = [ordered]@{ text = 'Grouping parent: the SSRF cluster that includes this finding.' }
        })
        properties = [ordered]@{ 'ai/exploitability' = 'poc'; 'ai/attackerPosition' = 'unauthenticated-remote' }
    })

    # runs[0].results[1] - unvalidated fetch; isIncludedBy the same cluster.
    Invoke-EmitResult $genHandle ([ordered]@{
        ruleId = 'CWE-918/unvalidated-fetch'
        level  = 'error'
        rank   = 75
        message = [ordered]@{
            text     = 'Outbound fetch targets an unvalidated, attacker-controlled URL.'
            markdown = '**CWE-918** - the fetch target derives from unvalidated request input, permitting requests to arbitrary internal hosts.'
        }
        locations = @([ordered]@{
            id = 0
            physicalLocation = [ordered]@{ artifactLocation = [ordered]@{ uri = 'src/api/proxy.ts'; uriBaseId = 'SRCROOT' }; region = [ordered]@{ startLine = 6 } }
            relationships = @([ordered]@{ target = 1; kinds = @('isIncludedBy') })
        })
        relatedLocations = @([ordered]@{
            id = 1
            physicalLocation = [ordered]@{ artifactLocation = [ordered]@{ uri = 'sarif:/runs/1/results/0' } }
            message = [ordered]@{ text = 'Grouping parent: the SSRF cluster that includes this finding.' }
        })
        properties = [ordered]@{ 'ai/exploitability' = 'theoretical'; 'ai/attackerPosition' = 'unauthenticated-remote' }
    })

    # runs[1].results[0] - the synthesized SSRF cluster; includes both raw findings.
    Invoke-EmitResult $synHandle ([ordered]@{
        ruleId = 'CWE-918/ssrf-via-unvalidated-fetch'
        level  = 'error'
        rank   = 90
        message = [ordered]@{
            text     = 'Unauthenticated SSRF reachable from the public ingress.'
            markdown = '**CWE-918** - a missing authentication check (CWE-306) and an unvalidated outbound fetch (CWE-918) together compose an unauthenticated server-side request forgery reachable from the public ingress.'
        }
        locations = @([ordered]@{
            id = 0
            physicalLocation = [ordered]@{ artifactLocation = [ordered]@{ uri = 'src/api/proxy.ts'; uriBaseId = 'SRCROOT' }; region = [ordered]@{ startLine = 8 } }
            relationships = @(
                [ordered]@{ target = 1; kinds = @('includes') },
                [ordered]@{ target = 2; kinds = @('includes') }
            )
        })
        relatedLocations = @(
            [ordered]@{ id = 1; physicalLocation = [ordered]@{ artifactLocation = [ordered]@{ uri = 'sarif:/runs/0/results/0' } }; message = [ordered]@{ text = 'Member: the missing authentication check.' } },
            [ordered]@{ id = 2; physicalLocation = [ordered]@{ artifactLocation = [ordered]@{ uri = 'sarif:/runs/0/results/1' } }; message = [ordered]@{ text = 'Member: the unvalidated outbound fetch.' } }
        )
        properties = [ordered]@{ 'ai/exploitability' = 'poc'; 'ai/attackerPosition' = 'unauthenticated-remote' }
    })

    Write-Host "[3/4] emit-finalize --inputs (order-preserving) --embed-text-files --validate"
    $finalizeArgs = @(
        $multitool, 'emit-finalize', $outPath,
        '--inputs', "$genHandle.wip.jsonl", "$synHandle.wip.jsonl",
        '--embed-text-files',
        '--validate'
    )
    & dotnet @finalizeArgs | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "emit-finalize failed (exit $LASTEXITCODE)." }

    Write-Host "[4/4] Wrote $outPath"
}
finally {
    foreach ($name in $savedCiEnv.Keys) {
        [System.Environment]::SetEnvironmentVariable($name, $savedCiEnv[$name])
    }
    Remove-Item $stageDir -Recurse -Force -ErrorAction SilentlyContinue
}
