// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Generic;

/// <summary>
/// Warning this comparer may not have all properties compared. Will be replaced by comprehensive
/// comparer generated by JSchema as part of EqualityComparer in a planned comprehensive solution.
/// Tracking by issue: https://github.com/microsoft/jschema/issues/141
/// </summary>
namespace Microsoft.CodeAnalysis.Sarif.Comparers
{
    internal class LocationComparer : IComparer<Location>
    {
        internal static readonly LocationComparer Instance = new LocationComparer();

        public int Compare(Location left, Location right)
        {
            if (ComparerHelper.CompareReference(left, right, out int compareResult))
            {
                return compareResult;
            }

            compareResult = left.Id.CompareTo(right.Id);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = PhysicalLocationComparer.Instance.Compare(left.PhysicalLocation, right.PhysicalLocation);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = ComparerHelper.CompareList<LogicalLocation>(left.LogicalLocations, right.LogicalLocations, LogicalLocationComparer.Instance);

            if (compareResult != 0)
            {
                return compareResult;
            }

            // Warning there may be properties are not compared.
            return compareResult;
        }
    }
}
