// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Generic;

/// <summary>
/// Note: This comparer may not have all properties compared. Will be replaced by comprehensive
/// comparer generated by JSchema as part of EqualityComparer in a planned comprehensive solution.
/// Tracking by issue: https://github.com/microsoft/jschema/issues/141
/// </summary>
namespace Microsoft.CodeAnalysis.Sarif.Comparers
{
    internal class LogicalLocationComparer : IComparer<LogicalLocation>
    {
        internal static readonly LogicalLocationComparer Instance = new LogicalLocationComparer();

        public int Compare(LogicalLocation left, LogicalLocation right)
        {
            if (ComparerHelper.CompareReference(left, right, out int compareResult))
            {
                return compareResult;
            }

            compareResult = string.Compare(left.Name, right.Name);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.Index.CompareTo(right.Index);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = string.Compare(left.FullyQualifiedName, right.FullyQualifiedName);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = string.Compare(left.DecoratedName, right.DecoratedName);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.ParentIndex.CompareTo(right.ParentIndex);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = string.Compare(left.Kind, right.Kind);

            if (compareResult != 0)
            {
                return compareResult;
            }

            // Note: There may be other properties are not compared.
            return compareResult;
        }
    }
}
