// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Generic;

/// <summary>
/// Warning this comparer may not have all properties compared. Will be replaced by comprehensive
/// comparer generated by JSchema as part of EqualityComparer in a planned comprehensive solution.
/// Tracking by issue: https://github.com/microsoft/jschema/issues/141
/// </summary>
namespace Microsoft.CodeAnalysis.Sarif.Comparers
{
    internal class MultiformatMessageStringComparer : IComparer<MultiformatMessageString>
    {
        internal static readonly MultiformatMessageStringComparer Instance = new MultiformatMessageStringComparer();

        public int Compare(MultiformatMessageString left, MultiformatMessageString right)
        {
            if (ComparerHelper.CompareReference(left, right, out int compareResult))
            {
                return compareResult;
            }

            compareResult = string.Compare(left.Text, right.Text);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = string.Compare(left.Markdown, right.Markdown);

            if (compareResult != 0)
            {
                return compareResult;
            }

            // Warning there may be properties are not compared.
            return compareResult;
        }
    }
}
