// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Generic;

/// <summary>
/// Note: This comparer may not have all properties compared. Will be replaced by comprehensive
/// comparer generated by JSchema as part of EqualityComparer in a planned comprehensive solution.
/// Tracking by issue: https://github.com/microsoft/jschema/issues/141
/// </summary>
namespace Microsoft.CodeAnalysis.Sarif.Comparers
{
    internal class PhysicalLocationComparer : IComparer<PhysicalLocation>
    {
        internal static readonly PhysicalLocationComparer Instance = new PhysicalLocationComparer();

        public int Compare(PhysicalLocation left, PhysicalLocation right)
        {
            if (ComparerHelper.CompareReference(left, right, out int compareResult))
            {
                return compareResult;
            }

            compareResult = ArtifactLocationComparer.Instance.Compare(left.ArtifactLocation, right.ArtifactLocation);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = RegionComparer.Instance.Compare(left.Region, right.Region);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = RegionComparer.Instance.Compare(left.ContextRegion, right.ContextRegion);

            if (compareResult != 0)
            {
                return compareResult;
            }

            // Note: There may be other properties are not compared.
            return compareResult;
        }
    }
}
