// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Generic;

/// <summary>
/// Note: This comparer may not have all properties compared. Will be replaced by a comprehensive
/// comparer generated by JSchema as part of EqualityComparer in a planned comprehensive solution.
/// Tracking by issue: https://github.com/microsoft/jschema/issues/141
/// </summary>
namespace Microsoft.CodeAnalysis.Sarif.Comparers
{
    internal class ResultComparer : IComparer<Result>
    {
        internal static readonly ResultComparer Instance = new ResultComparer();

        public int Compare(Result left, Result right)
        {
            int compareResult = 0;

            if (left.TryReferenceCompare(right, out compareResult))
            {
                return compareResult;
            }

            compareResult = string.Compare(left.RuleId, right.RuleId);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.RuleIndex.CompareTo(right.RuleIndex);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.Level.CompareTo(right.Level);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.Kind.CompareTo(right.Kind);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = MessageComparer.Instance.Compare(left.Message, right.Message);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = ArtifactLocationComparer.Instance.Compare(left.AnalysisTarget, right.AnalysisTarget);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.Locations.ListCompare(right.Locations, LocationComparer.Instance);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = string.Compare(left.Guid, right.Guid);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = string.Compare(left.CorrelationGuid, right.CorrelationGuid);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.OccurrenceCount.CompareTo(right.OccurrenceCount);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.CodeFlows.ListCompare(right.CodeFlows, CodeFlowComparer.Instance);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.BaselineState.CompareTo(right.BaselineState);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.Rank.CompareTo(right.Rank);

            if (compareResult != 0)
            {
                return compareResult;
            }

            // Note: There may be other properties are not compared.
            return compareResult;
        }
    }
}
