// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Generic;

/// <summary>
/// Note: This comparer may not have all properties compared. Will be replaced by a comprehensive
/// comparer generated by JSchema as part of EqualityComparer in a planned comprehensive solution.
/// Tracking by issue: https://github.com/microsoft/jschema/issues/141
/// </summary>
namespace Microsoft.CodeAnalysis.Sarif.Comparers
{
    internal class ThreadFlowLocationComparer : IComparer<ThreadFlowLocation>
    {
        internal static readonly ThreadFlowLocationComparer Instance = new ThreadFlowLocationComparer();

        public int Compare(ThreadFlowLocation left, ThreadFlowLocation right)
        {
            int compareResult = 0;

            if (left.TryReferenceCompares(right, out compareResult))
            {
                return compareResult;
            }

            compareResult = left.Index.CompareTo(right.Index);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = LocationComparer.Instance.Compare(left.Location, right.Location);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.Kinds.ListCompares(right.Kinds);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.NestingLevel.CompareTo(right.NestingLevel);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.ExecutionOrder.CompareTo(right.ExecutionOrder);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.ExecutionTimeUtc.CompareTo(right.ExecutionTimeUtc);

            if (compareResult != 0)
            {
                return compareResult;
            }

            compareResult = left.Importance.CompareTo(right.Importance);

            if (compareResult != 0)
            {
                return compareResult;
            }

            // Note: There may be other properties are not compared.
            return compareResult;
        }
    }
}
