name: Build Multitool for npm

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Multitool for npm
      run: ./scripts/BuildMultitoolForNpm.ps1
